on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: 185.212.128.177
          username: o251298
          password: Zapomni1parol
          server-dir: /smsbulks.ru/
          port: 21 # todo replace with your web hosts ftps port